### ISSUE TITLE
bug: $model parameters with flow name in yaml file doesn't work

### ISSUE THREAD

**Issue by shrivd-pfizer** [NVIDIA/NeMo-Guardrails#1135]
### Did you check docs and existing issues?

- [x] I have read all the NeMo-Guardrails docs
- [x] I have updated the package to the latest version before submitting this issue
- [x] (optional) I have used the develop branch
- [x] I have searched the existing issues of NeMo-Guardrails

### Python version (python --version)

3.11.1

### Operating system/version

Windows

### NeMo-Guardrails version (if you must use a specific version and not the latest

0.12.0

### Describe the bug

I am creating a custom guardrails

Below is my colang file:
```
define bot refuse to respond about input prompt
  "I'm sorry, I cannot assist with this request, since input message contain blocked keywords"

define flow check blocked keywords on input
  $response = execute ias_check_blocked_input_keywords 
  
  if $response['failed']
    if $config.custom_data.block_user_request
      if $config.enable_rails_exceptions
        create event KeywordInputRailsException(message=$response['output'])
    else
      bot refuse to respond about input prompt
```

This is the config.yaml file I am using 
```yaml
custom_data:
  block_user_request: false
  keyword_rail_data:
    blocked_input_keywords:
    - Water
    - Kill
  output_rails_options: {}
enable_rails_exceptions: true
models:
- engine: genai_llm
  model: gpt-4
  type: custom
- engine: genai_llm
  model: gpt-4o
  type: main
- engine: genai_embedding
  model: text-embedding-ada-002
  type: embeddings
rails:
  input:
    flows:
    - check blocked keywords on input $model=custom
```

When I am trying to run above this. It is throwing an error that "flow doesn't exists: check blocked keywords on input $model=custom" 

### Steps To Reproduce

I am creating a custom guardrails

Below is my colang file:
```
define bot refuse to respond about input prompt
  "I'm sorry, I cannot assist with this request, since input message contain blocked keywords"

define flow check blocked keywords on input
  $response = execute ias_check_blocked_input_keywords 
  
  if $response['failed']
    if $config.custom_data.block_user_request
      if $config.enable_rails_exceptions
        create event KeywordInputRailsException(message=$response['output'])
    else
      bot refuse to respond about input prompt
```

This is the config.yaml file I am using 
```yaml
custom_data:
  block_user_request: false
  keyword_rail_data:
    blocked_input_keywords:
    - Water
    - Kill
  output_rails_options: {}
enable_rails_exceptions: true
models:
- engine: genai_llm
  model: gpt-4
  type: custom
- engine: genai_llm
  model: gpt-4o
  type: main
- engine: genai_embedding
  model: text-embedding-ada-002
  type: embeddings
rails:
  input:
    flows:
    - check blocked keywords on input $model=custom
```

Throwing an error that "flow doesn't exists: check blocked keywords on input $model=custom" 

### Expected Behavior

Should use the custom model for running the checked blocked input flow as per the documentation. 

### Actual Behavior

Resulting in error that  "flow doesn't exists: check blocked keywords on input $model=custom"
