### ISSUE TITLE
Got an unexpected keyword argument '$1' while execution 

### ISSUE THREAD

**Issue by DJT777** [NVIDIA/NeMo-Guardrails#127]
Hello, I am wondering if you can shed light on this error?

`Error qa_chain_answer() got an unexpected keyword argument '$1' while execution qa_chain_answer`

I am using this flow:

```

#GUARDRAILS CONTENT
yaml_content = """
models:
- type: main
  engine: openai
  model: text-davinci-003
  
- type: embeddings
  engine: openai
  model: text-embedding-ada-002
"""
```

```

define user ask about university information
    "Can you tell me some basic information about the university?"
    "What is the mission statement of the university?"
    "Give me an overview of the campus facilities."
    "Tell me about the university's history and founding."
    "What are the values of the university?"
    "How can I schedule a campus tour?"
    "What are some of the campus facilities and amenities offered at the university?"
    "Are there any notable alumni from this university?"
    "What is the student-to-faculty ratio at the university?"
    "Can you provide information on upcoming events or important dates for prospective students?"

define flow user ask university information
    user ask about university information
    $answer = execute qa_chain_answer($last_user_message)
    bot $answer
```

```

def qa_chain_answer(query):
    ###history = ""
    ###input_dict = {"question": query, "chat_history": history}
    print("USER QUERY: " + query)
    history = [
        {"role": "user", "content": query}
    ]
    result = appRails.generate(messages=history)
    print(result)
    response = result['content']
    return response
```
