### ISSUE TITLE
[Feature Request] Bedrock Embedding model

### ISSUE THREAD

**Issue by austinmw** [NVIDIA/NeMo-Guardrails#139]
Hi, Bedrock has a couple of embedding models, in particular, "amazon.titan-embed-g1-text-02". I'd like to submit a feature request so that I can use this model:

```yaml
models:
  - type: embeddings
    engine: amazon_bedrock
    parameters:
      model_id: "amazon.titan-embed-text-v1"
```

I think this file needs to be updated?
https://github.com/NVIDIA/NeMo-Guardrails/blob/5f2541edb3e1115d48fc219e6e4d287d2d759ca1/nemoguardrails/embeddings/basic.py
