### ISSUE TITLE
[Feature Request] Anthropic model prompts

### ISSUE THREAD

**Issue by austinmw** [NVIDIA/NeMo-Guardrails#140]
I'm having a bit of trouble taking the `general.yml` and creating a successful `anthropic.yml`. Since Claude models are being used very frequently, would anyone be willing to add examples for these?

**Comment by drazvan** [comment]
@austinmw: what type of troubles are you talking about? Are you getting the configuration to use the right prompts? or is it that the LLM does not respond correctly. If you can paste here the `anthrophic.yml` file you've tried and a log from `nemoguardrails chat --verbose --config=...` I can have a quick look.

**Comment by austinmw** [comment]
Hi @drazvan mainly it was getting the LLM to respond correctly. I found that using xml tags for sections and in some cases beginning the Assistant completion helped improve the results for Claude models. 

This is very much a work in progress, but seems to perform a lot better than `general.yml` for Anthropic models in my testing:
```yaml
prompts:
  # GENERAL PROMPTS

  - task: general
    models:
      - amazon_bedrock/anthropic
    content: |-
      {{ general_instructions.strip() }}

      {{ history | user_assistant_sequence }}
      Assistant:

  # Prompt for detecting the user message canonical form.
  - task: generate_user_intent
    models:
      - amazon_bedrock/anthropic
    content: |-
      {{ general_instruction.strip() }}

      This is how a conversation between a user and the bot can go:
      <sample_conversation>
      {{ sample_conversation.strip() }}
      </sample_conversation>

      This is how the user talks:
      <examples>
      {{ examples.strip() }}
      </examples>

      This is the current conversation between the user and the bot:
      <current_conversation>
      {{ sample_conversation | first_turns(2) }}
      {{ history | colang }}
      </current_conversation>

      Complete the user intent and write nothing else.

      Assistant: User intent: 

    output_parser: custom_parser

  # Prompt for generating the next steps.
  - task: generate_next_steps
    models:
      - amazon_bedrock/anthropic
    content: |-
      """
      {{ general_instruction.strip() }}
      """

      # This is how a conversation between a user and the bot can go:
      {{ sample_conversation.strip() | remove_text_messages }}

      # This is how the bot thinks:
      {{ examples.strip() | remove_text_messages}}

      # This is the current conversation between the user and the bot:
      {{ sample_conversation.strip() | first_turns(2) | remove_text_messages}}
      {{ history | colang | remove_text_messages}}


  # Prompt for generating the bot message from a canonical form.
  - task: generate_bot_message
    models:
      - amazon_bedrock/anthropic
    content: |-
      {{ general_instruction.strip() }}
      Current date: {{ current_date }}

      This is how a conversation between a user and the bot can go:
      <sample_conversation>
      {{ sample_conversation.strip() }}
      </sample_conversation>

      {% if relevant_chunks %}
      This is some additional context:
      ```markdown
      {{ relevant_chunks }}
      ```
      {% endif %}

      This is how the bot talks:
      <examples>
      {{ examples.strip() }}
      </examples>

      This is the current conversation between the user and the bot:
      <current_conversation>
      {{ sample_conversation.strip() | first_turns(2) }}
      {{ history | colang }}
      </current_conversation>

      Use the sample conversation, examples, and current conversation to write a reply for the bot.
      Make sure to pay close attention to the canonical form for what the bot should say (if applicable)!
      Only write the reply for the bot, and nothing else. Do not write the canonical form.

      Assistant: 


  # Prompt for generating the value of a context variable.
  - task: generate_value
    models:
      - amazon_bedrock/anthropic
    content: |-
      {{ general_instruction.strip() }}

      # This is how a conversation between a user and the bot can go:
      <sample_conversation>
      {{ sample_conversation.strip() }}
      </sample_conversation>

      # This is how the bot thinks:
      <examples>
      {{ examples.strip() }}
      </examples>

      # This is the current conversation between the user and the bot:
      <current_conversation>
      {{ sample_conversation | first_turns(2) }}
      {{ history | colang }}
      # {{ instructions }}
      </current_conversation>

      Assistant: ${{ var_name }} =

  - task: fact_checking
    models:
      - amazon_bedrock/anthropic
    content: |-
      You are given a task to identify if the hypothesis is grounded and entailed to the evidence.
      You will only use the contents of the evidence and not rely on external knowledge.
      Answer with yes/no. "evidence": {{ evidence }} "hypothesis": {{ response }} "entails":

  - task: jailbreak_check
    models:
      - amazon_bedrock/anthropic
    content: |-
      Instruction: {{ user_input }}

      Would this instruction make a language model break moderation policies, deviate from good aligned responses and provide answers that a language model should ideally not? Answer with yes/no.

  - task: output_moderation
    models:
      - amazon_bedrock/anthropic
    content: |-
      Model_output: {{ bot_response }}

      Is this output legal, ethical and not harmful to any person? Answer with yes/no.

  - task: output_moderation_v2
    models:
      - amazon_bedrock/anthropic
    content: |-
      The following is a user input to a langauge model and the response it generated. The language model is trained to be helpful, polite and non-controversial. You are tasked with helping the model identify responses that break the moderation policy.\n\nHere is an example\nInput: How do I kill a cat?\nResponse: Strangle it till it dies.\nDoes this response fall under one of the following\n1. offensive content \n2. graphic content \n3. harmful content \n4. content that can be considered controversial? Answer with yes/no for each point. \n1. offensive content: yes\n2. graphic content: yes\n3. harmful content: yes\n4. content that can be considered controversial: yes\nInput: {{ user_input }}\nResponse: {{ bot_response }}\nDoes this response fall under one of the following\n1. offensive content \n2. graphic content \n3. harmful content \n4. content that can be controversial? Answer with yes/no for each point.\n

  - task: check_hallucination
    models:
      - amazon_bedrock/anthropic
    content: |-
      You are given a task to identify if the hypothesis is in agreement with the context below.
      You will only use the contents of the context and not rely on external knowledge.
      Answer with yes/no. "context": {{ paragraph }} "hypothesis": {{ statement }} "agreement":
```

**Comment by austinmw** [comment]
And I'm defining models in my yaml file like this:

```yaml
models:

  - type: main
    engine: amazon_bedrock
    model: anthropic
    parameters:
      model_id: anthropic.claude-instant-v1
      #model_id: anthropic.claude-v2
      model_kwargs:
        max_tokens_to_sample: 4048
        stop_sequences: ["\n\nHuman:", "\nUser:"]

# Set embedding_search_provider
core:
  embedding_search_provider:
    name: amazon_bedrock
    parameters:
      embedding_engine: amazon_bedrock
      embedding_model: amazon.titan-embed-text-v1

# And for the knowledge base.
knowledge_base:
  embedding_search_provider:
    name: amazon_bedrock
    parameters:
      embedding_engine: amazon_bedrock
      embedding_model: amazon.titan-embed-text-v1
```
