### ISSUE TITLE
How to register a custom task?

### ISSUE THREAD

**Issue by austinmw** [NVIDIA/NeMo-Guardrails#156]
Hi, I'd like to register a custom task. I've added these:

yaml file:
```yaml
  - task: summarize_preferences
    content: |-
      Read the below chat history and summarize the users preferences concisely.

      {{ history }}

      Assistant: Here is a summary of the users preferences:  
```

colang file:
```co
# Flow for generating recommendation
define flow
  bot fetch_recommendation
  $result = execute summarize_preferences
  $answer = execute qa_chain(user_message=$result)
  bot $answer
```

However I get the error:
`Action 'summarize_preferences' not found.`

Do I need to use `llm_rails.register_action()`? And if so, what should the function look like?
