### ISSUE TITLE
[Bug] WARNING: Parameter temperature does not exist for Bedrock

### ISSUE THREAD

**Issue by austinmw** [NVIDIA/NeMo-Guardrails#158]
Hi,

I noticed that `generation.py` does the following in several places:

```python
with llm_params(llm, temperature=self.config.lowest_temperature):
```

However it seems that for temperature to be passed to bedrock it would need to be:

```python
with llm_params(llm, model_kwargs={'temperature': self.config.lowest_temperature}):
```

I'm not sure of the cleanest way to make it compatible with both, but just wanted to alert you to this issue. Thanks!

**Comment by rgstephens** [comment]
I think this is related:

```yml
models:
  - type: main
    engine: deepinfra
    model: mistralai/Mixtral-8x7B-Instruct-v0.1
    parameters:
      model_kwargs:
        temperature: 0.5
```

Results in: `Parameter temperature does not exist for DeepInfra`

But, temperature is required for DeepInfra and results in the following error if not provided: `Parameter temperature does not exist for DeepInfra`
