### ISSUE TITLE
 install from source without Annoy/SentenceTransformers 

### ISSUE THREAD

**Issue by krannnn** [NVIDIA/NeMo-Guardrails#214]
Hello, 

in the [release notes](https://github.com/NVIDIA/NeMo-Guardrails/releases/tag/v0.5.0) of v0.5.0 it is mentioned:

> Refactored imports to allow installing from source without Annoy/SentenceTransformers (would need a custom embedding search provider to work).

@drazvan can you please help with the instructions/commands to install without Annoy/SentenceTransformers?

Thanks

**Comment by drazvan** [comment]
@krannnn: are you installing from source or the `0.5.0` version? For the latter, you would have to uninstall annoy/sentence transformers. For the former, you can remove them from requirements.txt before installing. 

The second step is to register a custom embedding search provider. See the second example here: https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/docs/user_guides/advanced/embedding-search-providers.md
```
core:
  embedding_search_provider:
    name: default
    parameters:
      embedding_engine: openai
      embedding_model: text-embedding-ada-002

knowledge_base:
  embedding_search_provider:
    name: default
    parameters:
      embedding_engine: openai
      embedding_model: text-embedding-ada-002
```

Let me know if this helps.
