### ISSUE TITLE
overwrite default configuration

### ISSUE THREAD

**Issue by szaher** [NVIDIA/NeMo-Guardrails#248]
Is there anyway to overwrite the default config available here https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/rails/llm/default_config.yml also https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/rails/llm/llm_flows.co ?

**Comment by drazvan** [comment]
For the default YAML config, yes, you just have to include those keys in your `config.yml`:

```yaml
sample_conversation: |
  << something else>>

instructions:
  - type: "general"
    content: |
      << something else>>
```

For the `llm_flows.co` it wouldn't make sense to override them, as they are needed for core functionality, e.g. run all the input rails. That being said, if you define other flows with the same name in your `.co` files, the will override the system ones.
