### ISSUE TITLE
I want to add Nemo Guardrail as layer on top of vLLM hosted LLM. 

### ISSUE THREAD

**Issue by SinhaPrateek** [NVIDIA/NeMo-Guardrails#391]
I want to add Nemo Guardrail as a layer on top of vLLM hosted LLM.  That means, I need to replace openai model with my vLLM hosted LLM.
One approahc seems to be to update the config.yml, but is it possible and what values of engine and model should be taken ?
models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo-instruct

**Comment by drazvan** [comment]
@SinhaPrateek : yes, it is possible. See this example: https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/examples/configs/llama_guard/config.yml. 
There, the Llama Guard model is configured through vLLM, but you can use a similar configuration for the main LLM as well. 

```yaml
models:
- type: main
  engine: vllm_openai
  parameters:
    openai_api_base: "http://localhost:5000/v1"
    model_name: "..."
```
