### ISSUE TITLE
ValueError: Invalid embedding engine: SentenceTransformer

### ISSUE THREAD

**Issue by pradeepdev-1995** [NVIDIA/NeMo-Guardrails#564]
Here is my ```config.yml``` content
```
instructions:
  - type: general
    content: |
      You are an AI assistant that supports ABC company based queries
rails:
  dialog:
    user_messages:
      embeddings_only: True
  input:
    flows:
      - self check input

core:
  embedding_search_provider:
    name: default
    parameters:
      embedding_engine: SentenceTransformer
      embedding_model: all-MiniLM-L6-v2
      use_batching: False
      max_batch_size: 10
      max_batch_hold: 0.01
```

But while running it shows the given error
```
ValueError: Invalid embedding engine: SentenceTransformer
Error in LoggingCallbackHandler.on_chat_model_start callback: TypeError('can only concatenate list (not "str") to list')
Error while execution generate_user_intent: Invalid embedding engine: SentenceTransformer
I'm sorry, an internal error has occurred.
```

**Comment by drazvan** [comment]
@pradeepdev-1995 : there's a typo. Should be "SentenceTransformers" (with an "s" at the end).

**Comment by pradeepdev-1995** [comment]
@drazvan 
Okay
i corrected like this and provided the local path for model
```
core:
  embedding_search_provider:
    name: default
    parameters:
      embedding_engine: SentenceTransformers
      model: /home/models--sentence-transformers/c46f31f8d119ac648208de9fba297c447a5a4474
      use_batching: False
      max_batch_size: 10
      max_batch_hold: 0.01
```
But still getting this error
```
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like sentence-transformers/all-MiniLM-L6-v2 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
Error in LoggingCallbackHandler.on_chat_model_start callback: TypeError('can only concatenate list (not "str") to list')
No sentence-transformers model found with name sentence-transformers/all-MiniLM-L6-v2. Creating a new one with MEAN pooling.
/home/.local/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
```
Should I specify anything else to make it local file readable?
