### ISSUE TITLE
generate_user_intent not working when self_check_input is followed by another action

### ISSUE THREAD

**Issue by kaustubhbhavsar** [NVIDIA/NeMo-Guardrails#668]
File Structure:
```
-config	
   -actions
	-process_input.py
    -rails
	-conversations.co
	-flows.co
    -config.yml
    -prompts.yml
-test.py
```

process_input.py:
```
from typing import Optional
from nemoguardrails.actions import action

@action(name="process_input")
def process_input(
    context: Optional[dict] = None,
):
    user_input = context.get("user_message")
    response = "Guardrails Passed ---> User Input: " + user_input
    return response
```

conversations.co:
```
define user express greeting
    "Hello!"
    "Hi"
    "Hey There!"
define bot express greeting
    "Welcome! I'm your AI assistant. How can I assist you today?"
define flow 
    user express greeting
    bot express greeting

```

flows.co
```
define flow self check input
  $allowed = execute self_check_input
  if not $allowed
    bot refuse to respond
    stop
    
define bot refuse to respond
    "Apologies, I can't answer that. Can I help with something else?"

define flow process input
    $answer = execute process_input
    bot $answer
```

test.py:
```
def main():
    config = RailsConfig.from_path("./config")
    rails = LLMRails(config=config, verbose=True)

    response = rails.generate(messages=[{
        "role": "user",
        "content": "Hey There!",
    }])
    print("Response: ", response)

    info = rails.explain()
    print(info.print_llm_calls_summary())


if __name__ == "__main__":
    main()
```

**If config.yml is as follows i.e. with 'process input':**
```
models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo-instruct

instructions:
  - type: general
    content: |
      .....
sample_conversation: |
      .....
rails:
  input:
    flows:
      - self check input
      - process input

  output:
    flows:
      - self check output
```

then the output is (topical rails are not called):
```
Response:  {'role': 'assistant', 'content': 'Guardrails Passed ---> User Input: Hey There!'}
Summary: 2 LLM call(s) took 1.24 seconds and used 295 tokens.

1. Task `self_check_input` took 0.65 seconds and used 166 tokens.
2. Task `self_check_output` took 0.59 seconds and used 129 tokens.

```

**If config.yml is as follows i.e. after removing 'process input':**
```
rails:
  input:
    flows:
      - self check input

  output:
    flows:
      - self check output

```
then the output is (topical rails are called correctly):
```
Response:  {'role': 'assistant', 'content': "Welcome! I'm your AI assistant. How can I assist you today?"}
Summary: 2 LLM call(s) took 1.22 seconds and used 573 tokens.

1. Task `self_check_input` took 0.65 seconds and used 166 tokens.
2. Task `generate_user_intent` took 0.57 seconds and used 407 tokens.
```

version used is: 0.9.1.1
