### ISSUE TITLE
How to configure off-topics inside config.yml file itself without an .co file

### ISSUE THREAD

**Issue by pradeepdev-1995** [NVIDIA/NeMo-Guardrails#682]
Currently I am using the nemo guardrail topical rail like this
i have a **config.yml** file
```
instructions:
  - type: general
    content: |
      You are an AI assistant that supports ABC company queries
rails:
  dialog:
    user_messages:
      embeddings_only: True
  input:
    flows:
      - self check input
```
Then **off-topic.co** file like this
```
define user ask off topic:
  "What are the main components of Refract?"
  "Can you provide a brief overview of Machine Learning in the context of Refract?"
  "What is Fosfor and how does it relate to Refract?"
  "How does Refract solve the challenge of organizations struggling to connect business value propositions to AI/ML models?"
  "How can Refract facilitate the transition from small-scale testing to enterprise-scale ML adoption?"
define bot explain cant off topic:
  "off topic"
define flow:
  user ask off topic
  bot explain cant off topic
```
Now i want to exclude the off-topic.co file and include everything( config details + off topic details)  in config.yml file. How to do that?Please put a sample example for this.
