### ISSUE TITLE
NeMo-Guardrails Container Setup: Production Jailbreak Functionality Not Working as Expected

### ISSUE THREAD

**Issue by mohilmakwana3107** [NVIDIA/NeMo-Guardrails#690]
I am following the instructions to integrate NeMo-Guardrails into my production environment. I cloned the repository and outsourced setting up the environment in a Docker container according to the file `jailbreak_cpu` [Dockerfile](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/library/jailbreak_detection/Dockerfile). The container build finished without any issues.

```
rails:
  config: 
    jailbreak_detection:
      server_endpoint: "http://0.0.0.0:1337/heuristics"
      length_per_plexity_threshold: 89.79
      prefix_suffix_perplexity_threshold: 1845.65 
```

Although when I try to make some use of the service in production, it returns this kind of error:

![image](https://github.com/user-attachments/assets/9cd0a488-87ad-4c6e-b937-6c8e24107524)

Despite the successful build, I am unable to achieve the expected functionality as described in the documentation. The error I receive when running the service is:

![image](https://github.com/user-attachments/assets/ea460a5a-535c-4284-bb5b-467567232be4)

I also tried curl from my pc : 
![image](https://github.com/user-attachments/assets/68bc65ca-6787-4604-80cc-ef05e6e1f40c)

I would appreciate any guidance on how to solve this problem or even understand if I'm missing any configurations for this setup.

Thank you!
