### ISSUE TITLE
Support for Azure OpenAi embedding model

### ISSUE THREAD

**Issue by shubhiroy** [NVIDIA/NeMo-Guardrails#692]
I'd like to propose adding support for the Azure OpenAI embedding model. My primary reason for this is to enable the use of the text-embedding-ada-002 model as the embedding model.

I believe this could be beneficial for those who are already using Azure's services or prefer to work within that ecosystem. I'm also happy to contribute to implementing this feature. Would there be any preference on how to integrate Azure OpenAI support? We could potentially add it in the configuration file, similar to other models.

```
  models:
    - type: main
      engine: openai
      model: text-davinci-003
   - type: embedding
     engine: azure
     model: text-embedding-ada-002
```
