### ISSUE TITLE
feature: Proposing Private AI integration for PII detection

### ISSUE THREAD

**Issue by letmerecall** [NVIDIA/NeMo-Guardrails#813]
### Did you check the docs?

- [x] I have read all the NeMo-Guardrails docs

### Is your feature request related to a problem? Please describe.

Add support for Private AI to safeguard Personally Identifiable Information and address one of the big safety concern for using LLMs.

### Describe the solution you'd like

To start with it'd be nice to have a Private AI PII detection action, something like `detect_pii` which can be used in input, output or retrival retrieval.

#### Example usage

```yaml
rails:
  input:
    flows:
      - detect pii on input
  output:
    flows:
      - detect pii on output
  retrieval:
    flows:
      - detect pii on retrieval
```

The implementation can be similar to what we already have for `sensitive_data_detection` action.

The implementation can be later extended to include:
- PII masking
- Synthetic entity generation

### Describe alternatives you've considered

We currently have an action `sensitive_data_detection` that uses Microsoft Presidio.
By introducing Private AI, we will expand support for more entities, improve detection accuracy, and provide additional features, including support for multiple file formats.

The support can also be extended to features like masking, synthetic entity genertion, and different file types.

### Additional resources
- Private AI developer docs: https://docs.private-ai.com/introduction/
- Supported entities: https://docs.private-ai.com/entities/
- Supported file types: https://docs.private-ai.com/files/
