### ISSUE TITLE
URGENT HELP NEED PLEASE: 'GuardRail output only' block my proper  message.

### ISSUE THREAD

**Issue by cathleenyuan** [NVIDIA/NeMo-Guardrails#827]
Hi , I have been really stuck on this issue for about 2 months time to set up a guard rail out put using Mxtral setting from our company , it does not working , much appreciate if anyone can give me some hand .

Config code as below

Config.yml

```yaml
instructions:
  - type: general
    content: |
      Below is a conversation between the ACompany's Technical Support Engineer and a Customer.
      Please make sure to use professional manners to talk to customers.      
      Rephrase if the language tone of words is not proper.
   
models:
  - type: main
    engine: nemo_llm
  - type: embeddings
    engine: SentenceTransformers
    model: /home/41284_SenstiveInformation_nemo/all-MiniLM-L6-v2
    

rails:
  output:
      flows:
      - self check output 
   ``` 

prompts.yml

```yaml
prompts:
  - task: self_check_output
    content: |
      Your task is to determine whether the bot response meets the A company policy, given the bot response.
      The Company policy states that the response should meet the following conditions:

      - it should not contain any explicit content, even if just a few words.
      - it should not contain abusive language or offensive content, even if just a few words.
      - it should not contain any harmful content.
      - it should not contain racially insensitive content.
      - it should not contain any word that can be considered offensive.
      - it should not contain PII/personal information.
      - it should not mention A competitors or their products.
      - it should not contain any proprietary information such as patents, trademarks, copyrights, or trade secrets.
      - it should not contain sensitive information, including politics, religion, race, gender, or geopolitical topics.
      - it should not contain any illicit/illegal guidelines.
      - it should not include any negative topics or comments about A, including bugs, problems, or customer service issues.
      - it should not mention non-A devices, products, or technologies unrelated to ACompany troubleshooting processes.
      - it should avoid humor, jokes, or any attempts at taking on different personas.
      - it should not discuss math questions, holiday information, famous people or celebrities, entertainment topics, or any other non-troubleshooting content unrelated to A.
      - it should not guide on performing factory resets or any actions that could harm a device or compromise its functionality.
      - it should not discuss environmental impact, technology trends, innovations, market share, cybersecurity, corporate social responsibility, industry partnerships, gaming products, educational initiatives, or future predictions.
      - it should not talk about topics such as weather, politics, entertainment, or any creative writing prompts like story or poem requests.

      Treat the above conditions as strict rules.
      If any of them are violated, you should block the bot's response by saying "No".
      If the response meets all the listed conditions, you should allow it by saying "Yes".
      Treat the above conditions as strict rules.

      Here is the bot response "{{ bot_response }}"
      
      Question: Should the above bot response be blocked ? please answer with either Yes or No.
      Answer [Yes/No]:

``` 

flow.co 

```
define bot refuse to respond
    "As a ACompany Technical Support Engineer, I cannot discuss this type of information with you."

define flow self check output
    $allowed = execute self_check_output

    if not $allowed 
        bot refuse to respond
        stop
    else
        $botresponse = execute b_response(input=$bot_response)
        bot $botresponse
        stop

``` 
config.py 

```python

from nemoguardrails.actions.actions import ActionResult
from nemoguardrails import LLMRails

async def func(input:str):
    # return input
    return ActionResult(return_value=input)

def init(app: LLMRails):
    # app.register_action(rag, "rag")
    app.register_action(action=func,name="b_response")

``` 

my LLM setup as below 

-------------------------------------------------------------------

# Define Custom LLM with async support

```python
# Define Custom LLM with async support
class LangchainDSXLLMMixtralForNemo(LLM):
    temperature: float = 0.01 

    @property
    def _llm_type(self) -> str:
        return "LangchainDSXLLMMixtral"

    def _call(
        self, 
        prompt: Union[str, dict], 
        stop: Optional[List[str]] = None, 
        run_manager: Optional[CallbackManagerForLLMRun] = None
    ) -> str:
        return self.invoke(prompt, stop, run_manager)

    def invoke(
        self, 
        prompt: Union[str, dict], 
        stop: Optional[List[str]] = None, 
        run_manager: Optional[CallbackManagerForLLMRun] = None
    ) -> str:
        messages = [{"role": "user", "content": prompt}]
    
        try:
            completion = client_mixtral.chat.completions.create(
                model="mixtral-8x7b-instruct-v01",
                messages=messages,
                temperature=0.01  # Use temperature here
            )
            
            response = completion.choices[0].message.content
            print('dsx_llm_nemo.py model response is ................................:', response)
            response = response.strip().lower()
            y_n_response = response
            
            if "yes" in response:
                y_n_response = "Yes"
            elif "no" in response:
                y_n_response = "No"
            print('dsx_llm_nemo.py model y_n_response is ................................:', y_n_response)
            
        except Exception as e:
            print(f"Error during model invocation: {e}")
            raise
            
        return y_n_response


    async def agenerate_prompt(
        self, prompt: List[str], callbacks=None, stop: Optional[List[str]] = None
    ) -> LLMResult:
        prompt_text = prompt[0].text
        result = await asyncio.to_thread(self.invoke, prompt_text, stop)
      
        generation = Generation(text=result)
        result_generation =LLMResult(generations=[[generation]])        
        return result_generation
        
    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        return {"temperature": self.temperature}
```

# Register custom LLM
```python

from nemoguardrails.llm.providers import register_llm_provider
from nemoguardrails import RailsConfig, LLMRails
NemoLLM = LangchainDSXLLMMixtralForNemo()
register_llm_provider("nemo_llm", NemoLLM)

# read the configuration of NemoGuardrails
config = RailsConfig.from_path("./nemo_config_output")
output_rails = LLMRails(config,llm=NemoLLM)

bot_response = "I will show you a link with the steps of reinstall laptop driver with links , is that sounds a good plan ?"  
    
guard_ouput_messages = [{"role": "context", "content": {"bot_response": bot_response}},
                           {"role": "user", "content": ""} ]


async def get_response():
    nemo_response_ouput = await output_rails.generate_async(messages=guard_ouput_messages, options={
        "rails" : ["output"]    })
    return nemo_response_ouput.response
   
import asyncio
loop = asyncio.get_event_loop()
response = loop.run_until_complete(get_response())

response
```
