### ISSUE TITLE
Integration with Databricks serving endpoint

### ISSUE THREAD

**Issue by azuretime** [NVIDIA/NeMo-Guardrails#902]
### Did you check the docs?

- [x] I have read all the NeMo-Guardrails docs

### Is your feature request related to a problem? Please describe.

Hi, there is no detail on how to use Nemo-Guardrails with Databricks serving endpoint in the docs. What should be the correct way to use the endpoints with a Databricks access token?

### Describe the solution you'd like

I have an existing RAG chain and want to use Nemo-Guardrails to filter input. Models in my notebook are loaded with **Databricks**(endpoint_name="endpoint_name",max_tokens=,temperature=) and **ChatDatabricks**(endpoint_name="endpoint_name",max_tokens=,temperature=). I know it's possible to use RunnableRails or "guardrails | some_chain" [(LangChain Integration)](https://docs.nvidia.com/nemo/guardrails/user_guides/langchain/langchain-integration.html) but I want the self check input step to be done before the retrieval step inside the chain. That means **if self check input decides the request should be blocked (Yes), the chain should reply with a default answer without retrieving any context. So how can I load the LLM from "endpoint_name" to check input inside the chain?** 

```
rails:
  input:
    flows:
      - self check input
``` 
Using the above rail, if the request pass the check, two tasks are performed:

Summary: 2 LLM call(s) took 5.13 seconds .
1. Task `self_check_input` took 2.46 seconds .
2. Task `general` took 2.67 seconds .

**How can I get the intermediate result from task 1 `self_check_input`  so that I can decide when to return my own default answer (Yes) or start retrieving context (No)?**

### Describe alternatives you've considered

Also, is something like Method 2 below possible?
In config.yml:
```
models:
  - type: main
    engine: "databricks_endpoint"
    model: "meta-llama-3-8b-instruct"
    headers:
          Authorization: "Bearer <your-access-token>"
    parameters:
      endpoint_url: https://..../serving-endpoints/meta-llama-3-8b-instruct/invocations
      task: "chat"
      model_kwargs:
        temperature: 0.5
        max_length: 64
```
