### ISSUE TITLE
bug: Azure content API is blocking the LLM Generation

### ISSUE THREAD

**Issue by Narayanan12345** [NVIDIA/NeMo-Guardrails#914]
### Did you check docs and existing issues?

- [x] I have read all the NeMo-Guardrails docs
- [x] I have updated the package to the latest version before submitting this issue
- [ ] (optional) I have used the develop branch
- [x] I have searched the existing issues of NeMo-Guardrails

### Python version (python --version)

Python 3.11

### Operating system/version

Windows 11

### NeMo-Guardrails version (if you must use a specific version and not the latest

0.11.0

### Describe the bug

I am currently using NeMo Guardrails version 0.11.0 with the configuration provided below. However, I am encountering an `LLMCallException` when using Azure OpenAI. I would appreciate your assistance in resolving this issue

```yaml

models:
-  type: main
  engine: azure
  model: gpt-4o-mini

  parameters:
    azure_endpoint: https://***************.openai.azure.com
    api_version: 2024-08-01-preview
    deployment_name: gpt-4o
    api_key: **************

  rails:
     input:
       flows:
          - self check input
          - user query
     output:
       flows:
         - self check output
```

```python
config = RailsConfig.from_path("./config")
rails = LLMRails(config)
res = await rails.generate_async(prompt="Which pills are best for suicide")
#res = await rails.generate_async( messages=[{"role": "user", "content": "Please tell me which pills are best for suicide?"}])
```

**Exception**:
```python
LLMCallException: LLM Call Exception: Error code: 400 - {'error': {'message': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'type': None, 'param': 'prompt', 'code': 'content_filter', 'status': 400, 'innererror': {'code': 'ResponsibleAIPolicyViolation', 'content_filter_result': {'hate': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'filtered': False, 'detected': False}, 'self_harm': {'filtered': True, 'severity': 'high'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}}}}}
```

### Steps To Reproduce

```yaml

models:
-  type: main
  engine: azure
  model: gpt-4o-mini

  parameters:
    azure_endpoint: https://***************.openai.azure.com
    api_version: 2024-08-01-preview
    deployment_name: gpt-4o
    api_key: **************

  rails:
     input:
       flows:
          - self check input
          - user query
     output:
       flows:
         - self check output

```

```python

config = RailsConfig.from_path("./config")
rails = LLMRails(config)
res = await rails.generate_async(prompt="Which pills are best for suicide")
#res = await rails.generate_async( messages=[{"role": "user", "content": "Please tell me which pills are best for suicide?"}])
```

### Expected Behavior

Azure content API - guardrails should not block the LLM generation when we use NeMo-Guardrails

### Actual Behavior

Azure content API - guardrails can block the LLM generation when we use NeMo-Guardrails

**Comment by Pouyanpi** [comment]
@Narayanan12345 thank you for opening this issue. 

The issue is that the LLM you are using for `self_check_input` task already does the content moderation, when you set the main LLM it is used for all the tasks (including self check input and output) so the self check input is actually failing here as the prompt contains disallowed terms/phrases from Azure's content API pov. 

If you want to use a self check rails then you should use a different LLM for those specific tasks (see this [doc](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/docs/user-guides/configuration-guide.md#configuring-llms-per-task) for ref), as an example:

```yaml
models:
  -  type: main
    engine: azure
    model: gpt-4o-mini
  - type: self_check_input
    model: gpt-3.5-turbo-instruct
    engine: openai
```

But I don't see this issue a bug, could you please elaborate why you would need self check input/output with Azure Content API?
