### ISSUE TITLE
Not hardcoded embedding models

### ISSUE THREAD

**Issue by jamescalam** [NVIDIA/NeMo-Guardrails#99]
Hi, I'd like to propose a fix to allow us to set the embedding model used to create the vector representations of rails. My reason for this is primarily that I'd like to be able to use a service like OpenAI for ada-002 primarily as an easy fix to large container sizes when deploying anything containing guardrails code — and additionally to allow us to select different hugging face models if preferred.

I'd propose in an initial version of this to support OpenAI and Hugging Face models. But very open to suggestions — I'd also be happy to work on this. Would there be any preference on how to set an embedding model? I figure we could do something in the config.yaml like:

```yaml
models:
  - type: main
    engine: openai
    model: text-davinci-003
 - type: embedding
   engine: openai
   model: text-embedding-ada-002
```

OR with hugging face:

```yaml
models:
  - type: main
    engine: openai
    model: text-davinci-003
 - type: embedding
   engine: huggingface
   model: sentence-transformers/all-MiniLM-L6-v2
```

**Comment by drazvan** [comment]
Hi @jamescalam! Your suggestion works. 

There is actually a minimal support for changing the embedding model, but still to a SentenceTransformer one. 
https://github.com/NVIDIA/NeMo-Guardrails/blob/main/nemoguardrails/actions/llm/generation.py#L73

See https://github.com/NVIDIA/NeMo-Guardrails/discussions/97 as well. 

```yaml
models:
   ...
   - type: embedding
     engine: SentenceTransformer
     model: all-MiniLM-L6-v2
```

We have a work in progress on a private branch to enable the integration of any embedding and search provider. There are a few things that are changing, including the interface for `EmbeddingsIndex` which needs to be async. I reckon next week we should be able to push this to the repo. And if you can, you can help with adding support for OpenAI as an `EmbeddingSearchProvider`. 

Thanks a lot!
